- name: Check apache2 server
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Sets Apache2 conf file
  template:
    src: "apache2.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}.conf"
    owner: www-data
    group: www-data
    mode: 0644

- name: Enable the Apache rewrite module
  command: a2enmod rewrite
  notify: Reload apache2

#- name: Enable the Apache rewrite module
#  command: a2enmod ssl
#  notify: Reload apache2

- name: Update a2ensite
  command: a2ensite {{ http_conf }}

- name: Enable new site
  file:
    src: "/etc/apache2/sites-available/{{ http_conf }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ http_conf }}.conf"
    state: link
  notify: Reload apache2

- name: Removes "default" site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: Reload apache2

#- name: Update a2ensite
#  command: a2ensite {{ app_root_dir }}

#- name: Enable the Apache rewrite module
#  command:  a2enmod rewrite

#  notify: Reload apache2
  

# UFW Configuration
- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

- name: "UFW - Allow HTTPS on port {{ http_port }}"
  ufw:
    rule: allow
    port: "443"
    proto: tcp
