---
- name: Update installed packages
  ansible.builtin.apt:
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600

- name: Install lsb-release apt-transport-https ca-certificates
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'lsb-release', 'apt-transport-https', 'ca-certificates' ]

- name: delete a file if it exists
  file:
    path: /etc/apt/trusted.gpg.d/php.gpg
    state: absent

- name: Download PPA for PHP8.1
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: Add the PPA to the server packages
  shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list

- name: Update installed packages
  ansible.builtin.apt:
    update_cache: yes
    autoclean: yes
    cache_valid_time: 3600
    force_apt_get: true

- name: Install PHP 8.1
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'php8.1', 'libapache2-mod-php8.1', 'php8.1-common', 'php8.1-mysql', 'php8.1-xml', 'php8.1-xmlrpc', 'php8.1-curl', 'php8.1-gd', 'php8.1-imagick', 'php8.1-cli', 'php8.1-dev', 'php8.1-imap','php8.1-mbstring', 'php8.1-opcache', 'php8.1-soap', 'php8.1-zip', 'php8.1-intl' ]

- name: Install PHP 8.1
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'php8.0', 'libapache2-mod-php8.0', 'php8.0-common', 'php8.0-mysql', 'php8.0-xml', 'php8.0-xmlrpc', 'php8.0-curl', 'php8.0-gd', 'php8.0-imagick', 'php8.0-cli', 'php8.0-dev', 'php8.0-imap','php8.0-mbstring', 'php8.0-opcache', 'php8.0-soap', 'php8.0-zip', 'php8.0-intl' ]
